"""Adiciona coluna status à tabela Compra

Revision ID: b2978f3440eb
Revises: 
Create Date: 2024-07-21 11:10:39.140737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2978f3440eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='Pendente'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
